[[docs]]
  name = "Prologue"
  weight = 10
  identifier = "prologue"
  url = "/docs/prologue/"

[[docs]]
  name = "Help"
  weight = 60
  identifier = "help"
  url = "/docs/help/"

[[main]]
  name = "Docs"
  url = "/docs/prologue/introduction/"
  weight = 10

# [[footer]]
#   name = "Privacy"
#   url = "/privacy-policy/"
#   weight = 10
